### ISSUE TITLE
html generation for tailwind

### ISSUE THREAD

**Issue by 8de2fdb0** [edger-dev/dioxus-class#11]
Why don't you generate the html files directly from the macro?

This 2 step process is very error prone.

**Comment by yjpark** [comment]
I just didn't figure out how to make it to be 1 step, to generate actual classes in HTML, I need to run the code, but to gather all the macros, I need to run the `cargo test` to hack the macro usages. Maybe it's possible, though it's not a trivial task for me.
I agree that the current way is a bit awkward, I'm using https://github.com/casey/just to simplify my use case, you can check the justfile for more details.
