### ISSUE TITLE
No documentation in rust code

### ISSUE THREAD

**Issue by pickfire** [edger-dev/dioxus-class#2]
People can see https://github.com/edger-dev/dioxus-class/tree/main/crates/dioxus-class but that requires developer to be online.

Would be good to be able to see documentation in https://docs.rs/dioxus-class/0.3.0/dioxus_class/index.html too.

**Comment by yjpark** [comment]
Documentation added in v0.5.0, also add doc strings for all constants, which is quite nice to have.

- https://docs.rs/dioxus-class/latest/dioxus_class/index.html
- https://docs.rs/dioxus-tailwindcss/0.5.0/dioxus_tailwindcss/layout/index.html
