### ISSUE TITLE
Tailwind not reading the value inside class! macro

### ISSUE THREAD

**Issue by codeitlikemiley** [edger-dev/dioxus-class#6]
go to any dioxus rust project

run command:

```sh
npx tailwindcss -i ./input.css -o ./src/assets/tailwind.css
```

on the render function 
```rust
rsx!(
        style { include_str!("./assets/tailwind.css") }
        header { class: class!(text_gray_400 bg_gray_900 body_font title_font),
... more code
```

start rust app

```
cargo run
or
dx serve --hot-reload --platform desktop
```

start modifying class! macro

```sh
 header { class: class!(text_pink_500 bg_gray_900 body_font title_font),
```

check your tailwind.css file
no changes

I dont think this is a problem with your project in rust...

but the tailwind command  , i guess it only knows how to parse something inside `class=` or `class:`
and it only parse in kebab-case not snake_case

I see your example it doest used the tailwind command, and just referencing tailwind cdn url...
which has all those classes already....

I believe the only solution here is to make those text inside the class! macro to resemble like in tailwind...
follow the kebab-case

**Comment by yjpark** [comment]
Just update the crates with Dioxus 0.5.0, also using a new way to generate class, all class! macro calls are gathered by using side effects in proc_macro, I think it's much better than a text base approach.

Check [BUILD.md](https://github.com/edger-dev/dioxus-class/blob/main/BUILD.md) for more details
